# pyproject.toml

[build-system]
requires = ["setuptools>=77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "life"
version = "0.1.0"
description = "Conway's Game of Life"
authors = [
    { name = "Itay Feldman", email = "itayfeldman@gmail.com" }
]
readme = "README.md"
license = { text = "LICENSE" }
requires-python = ">= 3.10"
keywords = ["automata"]
classifiers = [
    # How mature is this project? Common values are
    #   3 - Alpha
    #   4 - Beta
    #   5 - Production/Stable
    "Development Status :: 3 - Alpha",

    # Indicate who your project is intended for
    "Intended Audience :: Developers",

    # License
    "License :: OSI Approved :: MIT License",

    # Specify the Python versions you support here.
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",

    # Do not upload to PyP
    "Private :: Do Not Upload",
]

dependencies = [
    "python-dotenv",
    "matplotlib",
    "numpy",
    "scipy",
    "pygame",
    "mypy>=1.20.2",
]

[project.urls]
Homepage      = "https://github.com/itayfeldman/life"
Documentation = "https://github.com/itayfeldman/life/wiki"
Repo          = "https://github.com/itayfeldman/life.git"
Issues        = "https://github.com/itayfeldman/life/issues"

[tool.setuptools]
packages = ["life"]
package-dir = {"" = "src"}

[project.scripts]
life = "life.__main__:main"

[dependency-groups]
dev = [
    "pytest>=9.0.3",
]

[tool.mypy]
python_version = "3.12"
strict = true
files = ["src/"]
